name: Meu Primeiro Workflow

on:
  push:
    branches:
      - main

jobs:
  executar-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Mensagem inicial
        run: echo "Pipeline executada com sucesso!"

      - name: Criar e rodar script
        run: |
          echo "print('Olá do GitHub Actions!')" > script.py
          python3 script.py

      - name: Listar arquivos
        run: ls -la
